import './global.css';
import Footer from '@/components/footer/Footer';
import Navbar from '@/components/navbar/Navbar';
import { ThemeContextProvider } from '@/context/ThemeContext';
import ThemeProvider from '@/providers/ThemeProvider';

export const metadata = {
	title: 'Simple Blog App',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ThemeContextProvider>
					<ThemeProvider>
						<div className="container">
							<div className="wrapper">
								<Navbar />
								{children}
								<Footer />
							</div>
						</div>
					</ThemeProvider>
				</ThemeContextProvider>
			</body>
		</html>
	);
}
